server:
  port: 8080 # default
  shutdown: graceful

spring:
  output:
    ansi:
      enabled: always # log color

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect # JPA가 사용하는 sql을 mysql로 설정
    hibernate:
      ddl-auto: create # create: 재시작 시 테이블 지우고 다시 만듦 / update: 유지
    show-sql: false # JPA가 create 해주는 sql을 log로 남김. hibernate log 사용 시 false로 설정
    properties:
      hibernate:
      #        default_batch_fetch_size: 100 # 조회 시 배치 처리 (IN 쿼리)
      #        jdbc:
      #          batch_size: 100 # 입력/수정/삭제 시 batch size 만큼의 쿼리를 한번의 네트워크 통신으로 전송
      # sql 가독성 증가 (p6spy 사용 시 주석처리)
    #        format_sql: true # sql 포매팅 (줄 바꿈, 들여쓰기)
    #        highlight_sql: true # sql 키워드에 하이라이트 표시
    #        use_sql_comments: true # sql 주석
    open-in-view: false # DB 커넥션을 컨트롤러∙뷰 계층까지 유지할지 (default = true)

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa_study?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul # &rewriteBatchedStatements=true&logger=com.mysql.cj.log.Slf4JLogger&profileSQL=true
    username: root
    password: 1234
    hikari:
      auto-commit: false

# hibernate 로그 설정 (p6spy 사용 시 주석처리)
#logging:
#  level:
#    org.hibernate.SQL: DEBUG # hibernate sql log level
#    org.hibernate.orm.jdbc.bind: TRACE # 바인딩된 파라미터 값을 출력
#    org.hibernate.orm.jdbc.extract: TRACE # 쿼리로 읽어온 값 출력
#    org.springframework.transaction.interceptor: TRACE # 트랜잭션 관리와 관련된 동작 출력

# p6spy 로그 설정
logging:
  level:
    p6spy: info
